---
- name: install apache server on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      ansible.builtin.apt:
        name: apache2 
        update_cache: yes
        state: present
  
 
---
- name: install ngnix server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        state: latest