---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: tomcat installation
      ansible.builtin.user:
        name: install tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: 
        state: present    #waiting for next step