---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation        ##java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present 
    - name: create group tomcat      ## group create
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user tomcat       ## user create
      ansible.builtin.user:
        name: tomcat 
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present 
    - name: download tomcat 10.1.17  ## url (dont use this 1 its take 1 extra steps)
      ansible.builtin.get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz
        dest: /tmp//apache-tomcat-10.1.17.tar.gz
    - name: extract tomcat file 10.1.17   ## url (so use this 1 not upper 1)  (ask y upper 1 or this 1)
      ansible.builtin.unarchive:      
        src: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.17/bin/apache-tomcat-10.1.17.tar.gz 
        remote_src: yes
        dest: /opt/tomcat 
    - name: create symbolic link 
      ansible.builtin.file: 
        src: /opt/tomcat/apache-tomcat-10.1.17  
        dest: /opt/tomcat/latest 
        recurse: yes
        group: tomcat 
        owner: tomcat
        state: link
    - name: change owner and group permissions
      ansible.builtin.file:
        dest: /opt/tomcat
        owner: tomcat
        group: tomcat 
        recurse: yes                                    ## y we use ask
        state: directory                                ## y we use ask
        
for setting recursive permissions on the folder.
The next step to be automated is sudo sh -c 'chmod +x
